config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    concern :pictures do
      member do
        patch :upload_picture
      end
    end

    resources :users
    resources :pictures, only: [:destroy]
    resources :app_settings, only:[:index, :update]
    resources :news_posts
    resources :artists do
      concerns :pictures
    end
    resources :galleries do
      concerns :pictures
      resources :shows do
        concerns :pictures
      end   
    end

    root 'application#index'
  end
 
  devise_for :users
  
  resources :galleries, only: [:index, :show] do
    resources :shows, only: [:index, :show]
  end

  resources :artists, only: [:index, :show]
  resources :news_posts, only: [:index, :show]
  resources :app_settings, only:[:index]
  post "/contact_form", to: 'contact#index'
  root 'dashboard#index'
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  include Picturable
  validates :name, presence: true
  has_many :shows
  scope :visible, ->(){where(visible: true)}
  
  def self.get_first_image
    joins(:pictures).merge(Picture.where(sort: 0))
  end

  def to_s
    name
  end
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::ApplicationController
  before_action :set_gallery, except: [:index, :new, :create]

  def index
    @galleries = Gallery.all.includes(:shows)
  end

  def new
    @gallery = Gallery.new
    @gallery.pictures.build
  end

  def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      flash[:notice] = "Gallery : #{@gallery} has been created."
      redirect_to admin_galleries_path
    else
      flash[:alert] = "Gallery : #{@gallery} has failed to be created."
      render 'new'
    end
  end

  def destroy
    if @gallery.destroy
      flash[:notice] = "Gallery: #{@gallery} has been deleted."
      redirect_to admin_galleries_path
    else
      flash[:alert] = "Gallery: #{@gallery} has failed to be deleted."
      redirect_to admin_galleries_path
    end
  end

  def edit
  end

  def update
    if @gallery.update(gallery_params)
      flash[:notice] = "Gallery: #{@gallery} has been updated."
      redirect_to admin_galleries_path
    else
      flash.now[:alert] = "Gallery: #{@gallery} has failed to update."
      render 'edit'
    end
  end

  def upload_picture
    if @gallery.picture_save(gallery_params)
      render json: @gallery.pictures.last
    else
      render json: { errors: @gallery.errors.full_messages }, status: 422
    end
  end

  private

  def set_gallery
    @gallery = Gallery.find(params[:id])
  end

  def gallery_params
    params.require(:gallery).permit(
      :name, 
      :text, 
      :visible,
      pictures_attributes: Picture.settable_attrs 
    )
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    galleries = Gallery.all.visible.includes(:pictures).get_first_image
    render json: galleries, include: :pictures
  end

  def show
   gallery = Gallery.includes(:pictures).find(params[:id])
   render json: gallery, include: :pictures
  end
end

app/views/admin/galleries/_form.html.erb
<div class="container">
  <div class="col-md-12">
    <%= simple_form_for [:admin, gallery]  do |f| %>
      <%= f.input :name %>
      <%= f.input :visible %>
      <%= f.input :text, input_html: { class: 'summernote' }  %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/galleries/edit.html.erb
<header>Gallery Edit</header>

<ul class="nav nav-tabs" id="info_picture">
  <li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab" data-toggle="tab">Info</a></li>
  <li role="presentation"><a href="#pictures" aria-controls="pictures" role="tab" data-toggle="tab">Pictures</a></li>
</ul>



<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="info"><%= render "form", gallery: @gallery %>
  </div>
  <div role="tabpanel" class="tab-pane" id="pictures">
    <%= render "components/upload_pictures", objects: [@gallery] %>
    <%= render "components/sort_pictures", objects: [@gallery] %>
  </div>
</div>

app/views/admin/galleries/index.html.erb
<header>
  <h1>Galleries 
  <%= link_to "New Gallery", new_admin_gallery_path, class: "new" %> </h1>
</header>

<% @galleries.each do |gallery| %>
  <div class="panel panel-info">
    <div class="panel-heading control">
      <div class="row">
        <div class="col-md-4">
          <h4><%= gallery.name %></h4> Visible <span class="label label-default"><%= gallery.visible.to_s %></span>
        </div>
        <div class="col-md-4">
          <%= link_to "Edit", edit_admin_gallery_path(gallery), class: "edit navbar-btn" %>
          <%= link_to "Delete", 
            admin_gallery_path(gallery), 
            method: :delete,
            data: { confirm: "Are you sure you want to delete this Gallery #{gallery.name}?" },
            class: "delete navbar-btn"  %>
        </div>
        <div class="col-md-4"><a class="navbar-btn default collapsed" data-toggle="collapse" data-target="#show_<%= gallery.id %>" aria-expanded="false" aria-controls="show_<%= gallery.id %>"> Shows </a></div>
      </div>
      
    </div>
  <div class="bs-example"> 
   
    <div class="panel-body collapse" id="show_<%= gallery.id %>" aria-expanded="false" style="height: 0px;">
      <h4>Shows  <%= link_to "New Show", new_admin_gallery_show_path(gallery), class: "new" %></h4>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Text</th>
            <th>Artists</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% gallery.shows.each do |show| %>
          <tr>
            <td><%= show.title %></td>
            <td><%= table_text(show.text) %></td>
            <td><%= table_text(show.artists) %></td>
            <td><%= show.start_date %></td>
            <td><%= show.end_date %></td>
            <td> <%= link_to "Edit", edit_admin_gallery_show_path(gallery, show), class: "edit"%>
            <%= link_to "Delete", admin_gallery_show_path(gallery, show), method: :delete,
            data: { confirm: "Are you sure you want to delete this Artist: #{show.title}?" },
            class: "delete"  %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/admin/galleries/new.html.erb
<header>Create a Gallery</header>

<%= render "form", gallery: @gallery %>