config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    concern :pictures do
      member do
        patch :upload_picture
      end
    end

    resources :users
    resources :pictures, only: [:destroy]
    resources :app_settings, only:[:index, :update]
    resources :news_posts
    resources :artists do
      concerns :pictures
    end
    resources :galleries do
      concerns :pictures
      resources :shows do
        concerns :pictures
      end   
    end

    root 'application#index'
  end
 
  devise_for :users
  
  resources :galleries, only: [:index, :show] do
    resources :shows, only: [:index, :show]
  end

  resources :artists, only: [:index, :show]
  resources :news_posts, only: [:index, :show]
  resources :app_settings, only:[:index]
  post "/contact_form", to: 'contact#index'
  root 'dashboard#index'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  include Picturable
  def to_s
    name
  end
end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < Admin::ApplicationController
  before_action :set_user, except: [:index, :new, :create]

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      flash[:notice] = "Artist : #{@artist} has been created."
      redirect_to admin_artists_path
    else
      flash[:alert] = "Artist : #{@artist} has failed to be created."
      render 'new'
    end
  end

  def destroy
    if @artist.destroy
      flash[:notice] = "Artist: #{@artist} has been deleted."
      redirect_to admin_artists_path
    else
      flash[:alert] = "Artist: #{@artist} has failed to be deleted."
      redirect_to admin_artists_path
    end
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      flash[:notice] = "Artist: #{@artist} has been updated."
      redirect_to admin_artists_path
    else
      flash.now[:alert] = "Artist: #{@artist} has failed to update."
      render 'edit'
    end
  end

  def upload_picture
    params[:artist][:pictures_attributes]['0'][:sort] = @artist.pictures.count
    if @artist.picture_save(artist_params)
      render json: @artist.pictures.last
    else
      render json: { errors: @artist.errors.full_messages }, status: 422
    end
  end

  private

  def set_user
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:id, :name, :bio, pictures_attributes: [:image_file, :text, :id, :sort])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    render json: Artist.all
  end

  def show
    @artist = Artist.includes(:pictures).find(params[:id])
    render json: @artist, include: :pictures
  end
end

app/views/admin/artists/_form.html.erb
<%= simple_form_for [:admin, artist]  do |f| %>
  <%= f.input :name %>
  <%= f.input :bio, input_html: { class: 'summernote' }  %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/artists/edit.html.erb
<header>Artist Edit</header>

<ul class="nav nav-tabs" id="info_picture">
  <li role="presentation" class="active"><a href="#info" aria-controls="info" role="tab" data-toggle="tab">Info</a></li>
  <li role="presentation"><a href="#pictures" aria-controls="pictures" role="tab" data-toggle="tab">Pictures</a></li>
</ul>



<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="info">
   <%= render "form", artist: @artist %>
  </div>
  <div role="tabpanel" class="tab-pane" id="pictures">
    <%= render "components/upload_pictures", objects: [@artist] %>
     <%= render "components/sort_pictures", objects: [@artist] %>
  </div>
</div>

app/views/admin/artists/index.html.erb
<header>
  <h1>Artists</h1>
  <%= link_to "New Artist", new_admin_artist_path, class: "new" %>
</header>

<table id="artists" class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @artists.each do |artist| %>
    <tr>
      <td><%= artist.name %></td>
      <td><%=table_text(artist.bio)%></td>
      <td> <%= link_to "Edit", edit_admin_artist_path(artist), class: "edit"%>
      <%= link_to "Delete", admin_artist_path(artist), method: :delete,
      data: { confirm: "Are you sure you want to delete this Artist: #{artist.name}?" },
      class: "delete"  %></td>
    </tr>
  <% end %>
  </tbody>
<table>

app/views/admin/artists/new.html.erb
<header>Create a Artist</header>

<%= render "form", artist: @artist %>