config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    concern :pictures do
      member do
        patch :upload_picture
      end
    end

    resources :users
    resources :pictures, only: [:destroy]
    resources :app_settings, only:[:index, :update]
    resources :news_posts
    resources :artists do
      concerns :pictures
    end
    resources :galleries do
      concerns :pictures
      resources :shows do
        concerns :pictures
      end   
    end

    root 'application#index'
  end
 
  devise_for :users
  
  resources :galleries, only: [:index, :show] do
    resources :shows, only: [:index, :show]
  end

  resources :artists, only: [:index, :show]
  resources :news_posts, only: [:index, :show]
  resources :app_settings, only:[:index]
  post "/contact_form", to: 'contact#index'
  root 'dashboard#index'
end

app/models/news_post.rb
class NewsPost < ActiveRecord::Base
  scope :publish_ready, ->(){ where("publish_date < ?", Time.now) }
  scope :group_by_year, ->(){ group("DATE_TRUNC('year', publish_date)") }
  scope :by_year, ->(year){ where('extract(year from publish_date) = ?', year) }
  scope :select_for_links, ->(){ select([:id, :title, :publish_date])}
  
  def self.news_links_format
    links_by_year = {}
    counts_by_year ={}
    years_in_order = []

    publish_ready.group_by_year.count.each do |year, count| 
      year_str = year.strftime("%Y")
      years_in_order.push(year_str.to_i)
      links_by_year[year_str] = by_year(year_str).order(:publish_date).select_for_links.publish_ready
      counts_by_year[year_str] = count
    end
    
    return {
      years_in_order: years_in_order.sort! {|x,y| y <=> x } ,
      links_by_year: links_by_year ,
      counts_by_year: counts_by_year 
    }
  end

  def to_s
    title
  end

end

app/controllers/admin/news_posts_controller.rb
class Admin::NewsPostsController < Admin::ApplicationController
  before_action :set_news_post, except: [:index, :new, :create]

  def index
    @news_posts = NewsPost.all
  end

  def new
    @news_post = NewsPost.new
  end

  def create
    @news_post = NewsPost.new(news_post_params)
    if @news_post.save
      flash[:notice] = "NewsPost : #{@news_post} has been created."
      redirect_to admin_news_posts_path
    else
      flash[:alert] = "NewsPost : #{@news_post} has failed to be created."
      render 'new'
    end
  end

  def destroy
    if @news_post.destroy
      flash[:notice] = "NewsPost: #{@news_post} has been deleted."
      redirect_to admin_news_posts_path
    else
      flash[:alert] = "NewsPost: #{@news_post} has failed to be deleted."
      redirect_to admin_news_posts_path
    end
  end

  def edit
  end

  def update
    if @news_post.update(news_post_params)
      flash[:notice] = "NewsPost: #{@news_post} has been updated."
      redirect_to admin_news_posts_path
    else
      flash.now[:alert] = "NewsPost: #{@news_post} has failed to update."
      render 'edit'
    end
  end

  private

  def set_news_post
    @news_post = NewsPost.find(params[:id])
  end

  def news_post_params
    params.require(:news_post).permit(:title, :text, :publish_date)
  end
end

app/controllers/news_posts_controller.rb
class NewsPostsController < ApplicationController
  def index
    news_posts_links = NewsPost.all.news_links_format
    render json: news_posts_links
  end

  def show
    news_post = NewsPost.publish_ready.find(params[:id])
    render json: news_post
  end
end

app/views/admin/news_posts/_form.html.erb
<%= simple_form_for [:admin, news_post]  do |f| %>
  <%= f.input :title %>
  <%= f.input :publish_date %>
  <%= f.input :text, input_html: { class: 'summernote' }  %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/news_posts/edit.html.erb
<header>Artist News Post</header>

<%= render "form", news_post: @news_post %>

app/views/admin/news_posts/index.html.erb
<header>
  <h1>News Posts</h1>
  <%= link_to "New Post", new_admin_news_post_path, class: "new" %>
</header>

<table id="artists" class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>Publish Date</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @news_posts.each do |news_post| %>
    <tr>
      <td><%= news_post.title %></td>
      <td><%=table_text(news_post.text)%></td>
      <td><%= news_post.publish_date %></td>
      <td> <%= link_to "Edit", edit_admin_news_post_path(news_post), class: "edit"%>
      <%= link_to "Delete", admin_news_post_path(news_post), method: :delete,
      data: { confirm: "Are you sure you want to delete this New Post: #{news_post.title}?" },
      class: "delete"  %></td>
    </tr>
  <% end %>
  </tbody>
<table>

app/views/admin/news_posts/new.html.erb
<header>Create a News Post</header>

<%= render "form", news_post: @news_post %>