config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    concern :pictures do
      member do
        patch :upload_picture
      end
    end

    resources :users
    resources :pictures, only: [:destroy]
    resources :app_settings, only:[:index, :update]
    resources :news_posts
    resources :artists do
      concerns :pictures
    end
    resources :galleries do
      concerns :pictures
      resources :shows do
        concerns :pictures
      end   
    end

    root 'application#index'
  end
 
  devise_for :users
  
  resources :galleries, only: [:index, :show] do
    resources :shows, only: [:index, :show]
  end

  resources :artists, only: [:index, :show]
  resources :news_posts, only: [:index, :show]
  resources :app_settings, only:[:index]
  post "/contact_form", to: 'contact#index'
  root 'dashboard#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, except: [:index, :new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User has been created.'
      redirect_to admin_users_path
    else
      flash[:alert] = 'User has failed to be created.'
      render 'new'
    end
  end

  def destroy
    if @user == current_user
      flash[:alert] = 'You can not delete yourself.'
      redirect_to admin_users_path
    else
      if @user.destroy
        flash[:notice] = 'User has been deleted.'
        redirect_to admin_users_path
      else
        flash[:alert] = 'User has failed to be deleted.'
        redirect_to admin_users_path
      end
    end
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end
    if @user.update(user_params)
      flash[:notice] = 'User has been updated.'
      sign_in(@user, bypass: true) if @user == current_user
      redirect_to admin_users_path
    else
      flash.now[:alert] = 'User has failed to update.'
      render 'edit'
    end

  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, user] do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/users/edit.html.erb
<header>Edit <%= @user.email %></header>

<%= render "form", user: @user %>

app/views/admin/users/index.html.erb
<header>
  <h1>Users</h1>
  <%= link_to "New User", new_admin_user_path, class: "new" %>
</header>

<table id="users" class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Last Logged In</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.last_sign_in_at %></td>
      <td> <%= link_to "Edit", edit_admin_user_path(user), class: "edit"%>
      <%= link_to "Delete", admin_user_path(user), method: :delete,
      data: { confirm: "Are you sure you want to delete this #{user.email}?" },
      class: "delete"  %></td>
    </tr>
  <% end %>
  </tbody>
<table>

app/views/admin/users/new.html.erb
<header>Create a Admin User</header>

<%= render "form", user: @user %>